### ISSUE TITLE
Bug: Merging process overwrites already processed tiff files because of identical timestamp ID.

### ISSUE THREAD

**Issue by eogit** [clcr/pyeo#14]
In the aggregation subroutine, the timestamp of the SAFE directory is NOT a unique identifier of a Sentinel-2 scene. This is why in my processing run, out of 68 scenes only 30 merged tiff files are created - because some have different SAFE names but the same timestamp.

out_path = os.path.join(out_dir, get_sen_2_image_timestamp(safe_dir))+".tif"

The code needs to retain a unique identifier for each aggregated tif file with the full SAFE name.

**Comment by eogit** [comment]
This has now been fixed in my branch.

**Comment by Thingus** [comment]
Merged, will test.

**Comment by Thingus** [comment]
Closed in latest release
