### ISSUE TITLE
ValueError: could not broadcast input array from shape (4,11039,11039) into shape (4,11038,11039)

### ISSUE THREAD

**Issue by ValentinLouis** [clcr/pyeo#31]
I encountered this error twice:
1st error message:
File "/data/clcr/vmhl1/pyeo/pyeo/apps/change_detection/rolling_composite_s2_change_detection.py", line 121, in <module>
    pyeo.composite_directory(composite_merged_dir, composite_dir)
  File "/data/clcr/vmhl1/pyeo/pyeo/core.py", line 1089, in composite_directory
    composite_images_with_mask(sorted_image_paths, composite_out_path, format)
  File "/data/clcr/vmhl1/pyeo/pyeo/core.py", line 1028, in composite_images_with_mask
    np.copyto(output_view, in_masked, where=np.logical_not(in_masked.mask))
ValueError: could not broadcast input array from shape (4,11039,11039) into shape (4,11038,11039)
/data/clcr/vmhl1/pyeo/bin/rolling_s2_change_detection: line 5: 12208 Segmentation fault      python "$PYEO"/pyeo/apps/change_detection/rolling_composite_s2_change_detection.py "$@"

2nd error message:
File "/data/clcr/vmhl1/pyeo/pyeo/apps/change_detection/rolling_composite_s2_change_detection.py", line 121, in <module>
    pyeo.composite_directory(composite_merged_dir, composite_dir)
  File "/data/clcr/vmhl1/pyeo/pyeo/core.py", line 1089, in composite_directory
    composite_images_with_mask(sorted_image_paths, composite_out_path, format)
  File "/data/clcr/vmhl1/pyeo/pyeo/core.py", line 1028, in composite_images_with_mask
    np.copyto(output_view, in_masked, where=np.logical_not(in_masked.mask))
ValueError: could not broadcast input array from shape (4,11020,11020) into shape (4,11019,11020)
ERROR 1: CPLVirtualMemManagerThread: no mapping found
/data/clcr/vmhl1/pyeo/bin/rolling_s2_change_detection: line 5: 10594 Segmentation fault      python "$PYEO"/pyeo/apps/change_detection/rolling_composite_s2_change_detection.py "$@"

Here an additional error message occurs (CPLVirtualMemManagerThread: no mapping found) which might caused by my qsub settings.

Thanks

**Comment by Thingus** [comment]
This smells like a float rounding error; I'll give it a look over and see if I missed adding the fix to this function

**Comment by Thingus** [comment]
The problem seems to have been due to the location of the top-left pixel drifting due to reprojection. get_raster_bounds made the now-false assumption that these values would be integers; they are passed through np.floor() before any further operations are run, as of commit a3e5de2dbe2b29bba55bb2e879b1ad53c7d1d407.
I'm running it now with that data and it looks OK (got past the original sticking-point) but I'm not going to mark this issue as closed until I've seen an entire processing chain run with it.

**Comment by Thingus** [comment]
Of course, now the mask combination step fails due to a probably unrelated error.

**Comment by Thingus** [comment]
This hasn't turned up again in three months of heavy processing; calling it fixed.

**Comment by hidexxx** [comment]
Can confirm this. Was getting the same error for one path in Savanna window area in Ghana, after the update, the error discontinued.

**Comment by Thingus** [comment]
Ta!
