### ISSUE TITLE
Feature suggested for filtering search results for downloading?

### ISSUE THREAD

**Issue by hidexxx** [clcr/pyeo#4]
Was wondering, if it is worth adding a function for users who refined their searching results through the  interactive graphical user interface? So they can refine the search results in the user interface and download exactly what they want? 

This might be quite handy when (1) we only need to update certain images (2) a lot of visualisation of the search results is needed, e.g. small AOI in a quite cloudy areas

**Comment by Thingus** [comment]
I reckon it's a good idea; it'd be quite an involved process, though.
I'd like to see it once we've got the basic search-filter-download stream running; could be a job for after the next meeting?

**Comment by Thingus** [comment]
Amazingly, addressed (sort of) in aeac741ab00543a29899fbc523bc481438537723
You can now filter by L1 or L2, so I'm counting this as resolved.
