### ISSUE TITLE
srs error 

### ISSUE THREAD

**Issue by hidexxx** [clcr/pyeo#65]
Hi John, found out the reason for the projection error - the bug we fixed got committed to the Terrain brunch instead of the main one!
in the main brunch line 771, we are missing the srs_id argument
write_geometry(intersection, intersection_path, srs_id = srs_id)

**Comment by Thingus** [comment]
Ah, not a bug: the main branch now auto-detects the projection and assigns it itself.
I'll put the srs_id augment back in with a warning that it'll disappear for good soon.
