### ISSUE TITLE
gdal import causing errors

### ISSUE THREAD

**Issue by Calyppe** [clcr/pyeo#78]
Hello,

First of all, apologies if my language is not clear. I am not used to raising issues and discussing development.

When gdal is distributed through osgeo, the statement `import gdal` does not work, making the entire pyeo package not usable. Is it possible to change the import statement to `from osgeo import gdal` or use a try and catch structure to account for this situation?

Thank you!

**Comment by Thingus** [comment]
Hi @Calyppe 
I'm planning on updating the import statement in the next release to bring the library in line with Gdal 3.x, but there's a few other features I need to finish working on till then. In the meantime, would it be possible for you to pin your gdal version to 2.4.3?

**Comment by Calyppe** [comment]
Hi @Thingus 
Thank you for your reply. That's great to know. To be honest, it took me over 3 days to get gdal running properly on my computer, so I would rather not touch it anymore.
I made the change locally in my environment. So I can keep working. It just isn't ideal for sharing my work with colleagues. I can also fork the repo and use my copy in the .yml in the meantime.
I was not sure whether this issue had been raised before.

**Comment by Thingus** [comment]
Addressed in latest release
